### ISSUE TITLE
tradingview only default?

### ISSUE THREAD

**Issue by mirrormonark** [eouia/MMM-Widget2#1]
hello i'm trying this module and i wanted to configure it with tradingview like your example but customized. i don't understand why this happens: it shows me the widget but it shows me default settings, my configuration is never saved. what am i doing wrong? 

```
		{
			module: "MMM-Widget2",
			position: "top_left",
			pages: {"xxx":"top_left"},
			disabled: false,
			config: {
				code:`
					<!-- TradingView Widget BEGIN -->
					<div class="tradingview-widget-container">
					  <div class="tradingview-widget-container__widget"></div>
					  <div class="tradingview-widget-copyright"><a href="https://it.tradingview.com/" rel="noopener nofollow" target="_blank"></a></div>
					  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-forex-heat-map.js" async>
					  {
						"width": 1500,
						"height": 600,
						"currencies": [
							"EUR", 
							"USD", 
							"JPY", 
							"GBP", 
							"CNY", 
							"RUB", 
							"ZAR"
						], 
						"isTransparent": true,
						"colorTheme": "dark",
						"locale": "it"
					  },
						</script>
					</div>
					<!-- TradingView Widget END -->
					`,
				iframeStyle: {
					width: "1500px",
					height:"600px"
				},
				fullHTMLfile: true
			}
		},
```

**Comment by mirrormonark** [comment]
thank you if you answer me

**Comment by mirrormonark** [comment]
@eouia  @ulrichwisser

**Comment by eouia** [comment]
I’ll look inside in a few hours or days.

**Comment by mirrormonark** [comment]
@eouia thank you very much for your reply. i love this module but i would like to use it specifically with all tradingview widgets

**Comment by eouia** [comment]
What does it mean `your configuration`? It seems working normal.
![image](https://github.com/ulrichwisser/MMM-Widget2/assets/1720610/a52e2636-9626-4ce4-b2e3-1cea3d399f77)
What you expect and what you get? Tell us TO-BE and AS-IS more detailly.

**Comment by eouia** [comment]
I tried TradingView with my values;
![image](https://github.com/ulrichwisser/MMM-Widget2/assets/1720610/e0eea3b3-9ecf-4efd-96d6-66872072279b)

with this codes;
![image](https://github.com/ulrichwisser/MMM-Widget2/assets/1720610/75b8a55f-8844-49e4-bacf-de772ae98f8d)

**Comment by ulrichwisser** [comment]
Sorry for being late to the discussion. Somehow I didn't get any notification from github until @eouia pinged me.

@mirrormonark How is your configuration not saved? You have to save it first and then restart MM. Could you give us a sceenshot or some error messages?

**Comment by mirrormonark** [comment]
hi. i saved everytime my config.. but i dont restart the raspberry. i refresh the mirror.. but not working.. i try with:

- Technical Analysis Widget

- Ticker Tape Widget

- Forex Cross Rates Widget

-Forex Heatmap Widget

i want all this.. but one to one not working. i use page selector. one to work is Advanced Real﻿-﻿Time Chart Widget without restart raspberry.

**Comment by mirrormonark** [comment]
> I tried TradingView with my values; ![image](https://user-images.githubusercontent.com/1720610/245590635-e0eea3b3-9ecf-4efd-96d6-66872072279b.png)
> 
> with this codes; ![image](https://user-images.githubusercontent.com/1720610/245591059-75b8a55f-8844-49e4-bacf-de772ae98f8d.png)

i will try this and after save config i will try restart raspberry. one question: punctuation and spaces must be precise?

**Comment by eouia** [comment]
You don't need to `restart raspberry pi`; you just need `restart MagicMirror`.

**Comment by eouia** [comment]
> punctuation and spaces must be precise?

space is not so important.
for punctuation, each symbol has it's meaning. So you need carefulness.

**Comment by mirrormonark** [comment]
> You don't need to `restart raspberry pi`; you just need `restart MagicMirror`.

always clone magicmirror and when i start im writing.. "npm run start" everytime. i dont have mirror on 24h because i dont have finish my config. so if i start everytime.. is also like restart, or not?

**Comment by mirrormonark** [comment]
code: `
                                      <div class="tradingview-widget-container">
                                        <div class="tradingview-widget-container__widget"></div>
                                        <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text">Track all markets on TradingView</span></a></div>
                                        <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-forex-cross-rates.js" async>
                                        {
                                        "width": 770,
                                        "height": 400,
                                        "currencies": [
                                          "EUR",
                                          "USD",
                                          "JPY",
                                          "GBP",
                                          "CNY",
                                          "ISK",
                                          "INR",
                                          "SAR",
                                          "RUB",
                                          "COP"
                                        ],
                                        "isTransparent": true,
                                        "colorTheme": "dark",
                                        "locale": "en"
                                      }
                                        </script>
                                      </div>
                                      

> What does it mean `your configuration`? It seems working normal. ![image](https://user-images.githubusercontent.com/1720610/245588758-a52e2636-9626-4ce4-b2e3-1cea3d399f77.png) What you expect and what you get? Tell us TO-BE and AS-IS more detailly.

i see this but not my personal widget.

my config: 
`		{
			module: "MMM-Widget2",
			position: "top_left",
			pages: {"finance":"top_left"},
			disabled: false,
			config: {
				code:`

<div    class="tradingview-widget-container">
	<div class=   "tradingview-widget-container__widget"></div>
	<div class=   "tradingview-widget-copyright">
		<a href="https://it.tradingview.com/" rel="noopener nofollow" target="_blank">
		</a>
	</div>
	<script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-forex-heat-map.js" async>
	{
	"width": 1500,
	"height": 600,
	"currencies": [
		"EUR", 
		"USD", 
		"JPY", 
		"GBP", 
		"CNY", 
		"RUB", 
		"ZAR"
	], 
	"isTransparent": false,
	"colorTheme": "dark",
	"locale": "en"
},
	</script>
</div>

					`,
				iframeStyle: {
					width: "1500px",
					height:"600px"
				},
				fullHTMLfile: true
			}
		},
		{`

**Comment by mirrormonark** [comment]
> I tried TradingView with my values; ![image](https://user-images.githubusercontent.com/1720610/245590635-e0eea3b3-9ecf-4efd-96d6-66872072279b.png)
> 
> with this codes; ![image](https://user-images.githubusercontent.com/1720610/245591059-75b8a55f-8844-49e4-bacf-de772ae98f8d.png)

ok with this code it works. i think each  "<div<, <a<, <span<" (just for see) must have its own line... i used to copy and paste as it was...you have to not only copy and paste the code but pay attention to the header of the code. i think i will close this post as solved. i have one question, is this module good for both 32bit and 64bit? @ulrichwisser @eouia I ask because the animated widget (Ticker Tape Widget) I see it very slow and almost jerky.

**Comment by mirrormonark** [comment]
thank you so much for resolution.

**Comment by eouia** [comment]
> i have one question, is this module good for both 32bit and 64bit? @ulrichwisser @eouia I ask because the animated widget (Ticker Tape Widget) I see it very slow and almost jerky.


This module does nothing but only display simple html(with widget's JavaScript), so if your view is slow, your device itself is slow.
(The script of the widget  may be heavy for your system)

**Comment by mirrormonark** [comment]
so are you telling me that I need to upgrade to 64bit, increase the ram on the raspberry from 8gb to 16/32gb (Either by replacing the ram itself or by taking some from the ssd) , and use an ssd to upgrade the device?

**Comment by eouia** [comment]
There could be various reasons which can give stress to the system to work slow.
 Maybe too many background jobs are taking the resources, or but just one big task would do also. Maybe your OS or dependencies might be too outdated so other components might not work together well. Or just too many processes are working on your MM. Or,…

I cannot say anything what is the reason of slowness of your system.  Not only HW issues, but also what happens in.

**Comment by mirrormonark** [comment]
thank you
